### PR TITLE
Read region from config when init s3 bucket

### PR DESCRIPTION
**Pull request by heskymatic**

### CODE REVIEW

**Comment by schickling** [comment]
Could you please adjust the readme and provide a default value in order to avoid breaking changes?

**Comment by heskymatic** [comment]
@schickling I have given a default value in the __construct function. 

I don't think readme need any update. 

The only place invoke the __construct function had been updated with matching parameters, which all read from config, which all should been set up beforehand. The region config already had default value too. 

Hope it's good to merge now.

**Comment by schickling** [comment]
LGTM. Could you please also adjust the tests? :)

**Comment by heskymatic** [comment]
@schickling test updated

**Comment by heskymatic** [comment]
Good to merge?

**Comment by schickling** [comment]
I'm not sure if the tests worked before but they still seem to fail in travis. Could you please look into this?

Side note: I'm no longer using this package on my own.

**Comment by heskymatic** [comment]
I believe the code and the test are fine. Travis complained an dependency failure for php 5.3 only. You might want to consider remove support for php 5.3.

**Comment by schickling** [comment]
Done! :+1:

**Pull request merged**
